global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - /etc/prometheus/alerts/alert.rules
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:7090 # Prometheus will be running
  - job_name: cosmos
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:55660 # Port Prometheus from Nolus
        labels: {}
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:9100 # Port node-exporter
        labels:
          instance: nolus-rila
  - job_name: validators
    metrics_path: /metrics/validators
    static_configs:
      - targets:
          - 127.0.0.1:9300 # Port node-exporter
        labels: {}
  - job_name: validator
    metrics_path: /metrics/validator
    relabel_configs:
      - source_labels:
          - address
        target_label: __param_address
    static_configs:
      - targets:
          - 127.0.0.1:9300 # Port cosmos-exporter
        labels:
          address: # validator-address
  - job_name: wallet
    metrics_path: /metrics/wallet
    relabel_configs:
      - source_labels:
          - address
        target_label: __param_address
    static_configs:
      - targets:
          - 127.0.0.1:9300  # Port cosmos-exporter
        labels:
          address: # nolus-address
